services:
  ros-humble-dev:
    build: .
    image: ros2-humble:latest
    command: bash
    stdin_open: true
    tty: true
    network_mode: "host"
    privileged: true

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      # Mount the current directory to the workspace for development
      - .:/home/rosuser/ros2_ws

    working_dir: /home/rosuser/ros2_ws
